spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration
    username: 'root'
    password: ''
  jpa:
    hibernate.ddl-auto : create
    generate-ddl: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: rendi
    password: rendi

    properties:
      mail:
        smptp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000